### ISSUE TITLE
GError thrown on linux

### ISSUE THREAD

**Issue by alesniak303** [AzureAD/microsoft-authentication-extensions-for-java#28]
I'm seeing the following when trying to obtain a token on Linux. 

Structure.getFieldOrder() on class com.microsoft.aad.msal4jextensions.persistence.linux.GError returns names ([code, domain, message]) which do not match declared field names ([])

I'm using msal4j on a Dockerized debian-10.5-slim image which does not have libsecret preinstalled.

I've installed the libsecret-1-0 package to fulfill the dependency and Java appears to be loading the library.

If there is additional configuration that is needed in support of this scenario, I haven't been able to find documentation relevant to it.  Libsecret documentation that I've found does not seem to address any configuration.

**Comment by SomkaPe** [comment]
@alesniak303  issue should be fixed in 1.1.0 release, thanks for reporting an issue.

**Comment by UmeshIghe** [comment]
@SomkaPe  This issue still persists in 1.1.0 release.
`at com.sun.jna.Structure.getFieldValue(Structure.java:639)
        at com.sun.jna.Structure.deriveLayout(Structure.java:1285)
        at com.sun.jna.Structure.calculateSize(Structure.java:1159)
        at com.sun.jna.Structure.calculateSize(Structure.java:1111)
        at com.sun.jna.Structure.useMemory(Structure.java:350)
        at com.sun.jna.Structure.<init>(Structure.java:202)
        at com.sun.jna.Structure.<init>(Structure.java:193)
        at com.sun.jna.Structure.<init>(Structure.java:189)
        at com.microsoft.aad.msal4jextensions.persistence.linux.GError.<init>(GE
        at com.microsoft.aad.msal4jextensions.persistence.linux.KeyRingAccessor.
        at com.microsoft.aad.msal4jextensions.persistence.linux.KeyRingAccessor.
        at com.store.LinuxCredentialStore.getToken(Linu
        at com.store.LinuxCredentialStore.getAccessToke
        at com.auth.AuthenticationFacade.getAccessToken
        at com.auth.GetTokenFromHeracles.main(GetTokenF
Caused by: java.lang.IllegalAccessException: Class com.sun.jna.Structure can not
        at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
        at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleOb
        at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:
        at java.lang.reflect.Field.get(Field.java:390)
        at com.sun.jna.Structure.getFieldValue(Structure.java:636)`

**Comment by yogeshVU** [comment]
we are too seeing this issue when running on linux
